#!/usr/bin/env bash
# ============================================================================
# Smart Hotel - Environment Generator Script
# ============================================================================
# This script generates a complete .env file with secure random secrets.
# External service credentials (Twilio, Telegram, SMTP) must be added manually.
#
# Usage:
#   ./generate-env.sh              # Generate new .env file
#   ./generate-env.sh --force      # Overwrite existing .env file
#   ./generate-env.sh --help       # Show this help
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ENV_EXAMPLE="${SCRIPT_DIR}/.env.example"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored output
info() { echo -e "${BLUE}ℹ${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; }

# Generate a random string
generate_secret() {
    local length=${1:-32}
    openssl rand -base64 "$length" 2>/dev/null | tr -d '/+=' | head -c "$length"
}

# Generate a hex string
generate_hex() {
    local length=${1:-32}
    openssl rand -hex "$length" 2>/dev/null
}

# Generate a secure password with mixed character types
# Requirements: 8+ chars, uppercase, lowercase, numbers, special chars
generate_secure_password() {
    local length=${1:-16}
    # Generate base random string and ensure all character classes present
    local base=$(openssl rand -base64 32 2>/dev/null | tr -d '/+=' | head -c $((length-4)))
    # Add required character classes: uppercase, lowercase, number, special
    local upper=$(echo "ABCDEFGHIJKLMNOPQRSTUVWXYZ" | fold -w1 | shuf | head -1)
    local lower=$(echo "abcdefghijklmnopqrstuvwxyz" | fold -w1 | shuf | head -1)
    local number=$(echo "0123456789" | fold -w1 | shuf | head -1)
    local special=$(echo "!@#%^&*" | fold -w1 | shuf | head -1)
    # Combine and shuffle
    echo "${base}${upper}${lower}${number}${special}" | fold -w1 | shuf | tr -d '\n'
}

# Show help
show_help() {
    cat << EOF
Smart Hotel Environment Generator

Usage: $0 [OPTIONS]

Options:
  --force    Overwrite existing .env file without confirmation
  --help     Show this help message

This script generates a .env file with secure random secrets for all services:
  • PostgreSQL passwords
  • InfluxDB tokens
  • Django secret keys
  • Node-RED credential secrets
  • Grafana admin password
  • Kiosk secret key

External service credentials must be configured manually:
  • Twilio (SMS) - Get from https://console.twilio.com/
  • Telegram (Bot) - Create via @BotFather
  • SMTP (Email) - Your email provider settings

EOF
}

# Check if openssl is available
check_dependencies() {
    if ! command -v openssl &> /dev/null; then
        error "openssl is required but not installed."
        echo "Install it with:"
        echo "  Ubuntu/Debian: sudo apt install openssl"
        echo "  macOS: brew install openssl"
        echo "  Fedora/RHEL: sudo dnf install openssl"
        exit 1
    fi
}

# Update Grafana datasource config with InfluxDB token
update_grafana_datasource() {
    local token="$1"
    local GRAFANA_DS_FILE="${SCRIPT_DIR}/config/grafana/provisioning/datasources/influxdb.yaml"
    
    if [[ -f "$GRAFANA_DS_FILE" ]]; then
        info "Updating Grafana InfluxDB datasource with token..."
        
        # Use sed to replace the token line
        if sed -i "s|token:.*|token: ${token}|" "$GRAFANA_DS_FILE" 2>/dev/null; then
            success "Grafana datasource updated with InfluxDB token"
        else
            warn "Could not update Grafana datasource - update manually in:"
            echo "    $GRAFANA_DS_FILE"
            echo "    Set: token: ${token}"
        fi
    else
        warn "Grafana datasource file not found: $GRAFANA_DS_FILE"
    fi
}

# Generate .env file
generate_env() {
    info "Generating secure secrets..."
    echo ""

    # Generate all secrets
    local POSTGRES_PASSWORD=$(generate_secret 32)
    local INFLUX_ADMIN_PASSWORD=$(generate_secret 32)
    local INFLUX_TOKEN=$(generate_hex 32)
    local DJANGO_SECRET_KEY=$(generate_secret 64)
    local GRAFANA_ADMIN_PASSWORD=$(generate_secret 24)
    local NODERED_CREDENTIAL_SECRET=$(generate_hex 32)
    local KIOSK_SECRET_KEY=$(generate_secret 64)
    local KIOSK_API_TOKEN=$(generate_hex 32)

    # Create .env file
    cat > "$ENV_FILE" << EOF
# ============================================================================
# Smart Hotel Cloud Infrastructure - Environment Configuration
# ============================================================================
# Generated on: $(date -Iseconds)
# Generated by: generate-env.sh
#
# IMPORTANT: Never commit this file to version control!
# ============================================================================

# ============================================================================
# TIMEZONE
# ============================================================================
TIMEZONE=UTC

# ============================================================================
# SESSION SETTINGS (7 days for hotel guests)
# ============================================================================
SESSION_COOKIE_AGE=604800

# ============================================================================
# POSTGRESQL - Main Application Database
# ============================================================================
POSTGRES_DB=smarthotel
POSTGRES_USER=smarthotel
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ============================================================================
# INFLUXDB - Time-Series Database
# ============================================================================
INFLUX_PORT=8086
INFLUX_ADMIN_USER=admin
INFLUX_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
INFLUX_ORG=smarthotel
INFLUX_BUCKET=sensors
INFLUX_RETENTION=0
INFLUX_TOKEN=${INFLUX_TOKEN}

# ============================================================================
# MQTT - Mosquitto Broker
# ============================================================================
MQTT_PORT=1883
MQTT_WS_PORT=9001

# ============================================================================
# DJANGO DASHBOARD
# ============================================================================
DASHBOARD_PORT=8001
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_DEBUG=False
DJANGO_ALLOWED_HOSTS=dashboard.saddevastator.qzz.io,localhost,127.0.0.1

# ============================================================================
# GRAFANA
# ============================================================================
GRAFANA_PORT=3000
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=\${GRAFANA_ADMIN_PASSWORD}
GRAFANA_ROOT_URL=https://grafana.saddevastator.qzz.io

# ============================================================================
# KIOSK - Guest Registration Terminal
# ============================================================================
KIOSK_PORT=8002
KIOSK_SECRET_KEY=${KIOSK_SECRET_KEY}
KIOSK_DEBUG=0
KIOSK_ALLOWED_HOSTS=*
KIOSK_API_TOKEN=${KIOSK_API_TOKEN}

# ============================================================================
# NODE-RED - SMS Gateway (Headless)
# ============================================================================
NODERED_PORT=1880
NODERED_CREDENTIAL_SECRET=${NODERED_CREDENTIAL_SECRET}

# ============================================================================
# TWILIO - SMS Integration (via Node-RED)
# ============================================================================
# Get these from https://console.twilio.com/
# Leave empty to disable SMS functionality
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=

# ============================================================================
# TELEGRAM - Bot Notifications (Optional)
# ============================================================================
# Create a bot with @BotFather: https://t.me/botfather
# Get chat ID: https://api.telegram.org/bot<TOKEN>/getUpdates
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# ============================================================================
# SMTP - Email Configuration (Optional)
# ============================================================================
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=true
SMTP_FROM=noreply@example.com
EOF

    success ".env file generated successfully!"
    
    # Update Grafana datasource with the generated token
    update_grafana_datasource "$INFLUX_TOKEN"
    
    echo ""
    
    # Print summary
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    info "Generated secrets for:"
    echo "  • PostgreSQL password"
    echo "  • InfluxDB admin password and token"
    echo "  • Django secret key"
    echo "  • Grafana admin password"
    echo "  • Node-RED credential secret"
    echo "  • Kiosk secret key and API token"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    warn "You still need to configure manually:"
    echo ""
    echo "  ${YELLOW}Twilio (SMS):${NC}"
    echo "    1. Create account at https://console.twilio.com/"
    echo "    2. Get Account SID and Auth Token"
    echo "    3. Get or buy a phone number"
    echo "    4. Update TWILIO_* variables in .env"
    echo ""
    echo "  ${YELLOW}Telegram (Notifications):${NC}"
    echo "    1. Message @BotFather on Telegram"
    echo "    2. Create a new bot with /newbot"
    echo "    3. Copy the bot token"
    echo "    4. Start a chat with your bot"
    echo "    5. Get chat ID from: https://api.telegram.org/bot<TOKEN>/getUpdates"
    echo "    6. Update TELEGRAM_* variables in .env"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    success "Ready to deploy! Run: docker compose up -d"
    echo ""
}

# Main
main() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║           Smart Hotel - Environment Generator                   ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""

    # Parse arguments
    FORCE=false
    for arg in "$@"; do
        case $arg in
            --force)
                FORCE=true
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            *)
                error "Unknown option: $arg"
                echo "Use --help for usage information."
                exit 1
                ;;
        esac
    done

    # Check dependencies
    check_dependencies

    # Check if .env already exists
    if [[ -f "$ENV_FILE" ]]; then
        if [[ "$FORCE" == "true" ]]; then
            warn "Overwriting existing .env file (--force specified)"
            # Backup existing file
            cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
            info "Backup saved to ${ENV_FILE}.backup.*"
        else
            error ".env file already exists!"
            echo ""
            echo "Options:"
            echo "  1. Use --force to overwrite (creates backup)"
            echo "  2. Manually edit the existing .env file"
            echo "  3. Delete .env and run this script again"
            echo ""
            exit 1
        fi
    fi

    generate_env
}

main "$@"
