# Generated by Django 5.2.10 on 2026-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'db_table': 'documents_documentaccesslog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('drivers_license', "Driver's License"), ('visa', 'Visa'), ('registration_form', 'Registration Form'), ('signature', 'Signature'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='guest_documents/%Y/%m/')),
                ('kiosk_file_path', models.CharField(blank=True, max_length=500)),
                ('kiosk_file_url', models.URLField(blank=True, max_length=500)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('frontdesk', 'Front Desk'), ('kiosk', 'Kiosk')], default='frontdesk', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Document',
                'verbose_name_plural': 'Guest Documents',
                'db_table': 'documents_guestdocument',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
