# Generated by Django 4.2.27 on 2025-12-29 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('temperature', models.FloatField(default=22.0)),
                ('humidity', models.FloatField(default=50.0)),
                ('luminosity', models.IntegerField(default=0)),
                ('gas_level', models.IntegerField(default=0)),
                ('target_temperature', models.FloatField(default=22.0)),
                ('heating_status', models.BooleanField(default=False)),
                ('mqtt_topic_prefix', models.CharField(blank=True, max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('luminosity', models.IntegerField(default=0)),
                ('gas_level', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_history', to='rooms.room')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
