# Generated by Django 4.2.27 on 2026-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='climate_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('off', 'Off')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='fan_speed',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
