# Generated by Django 4.2.27 on 2026-01-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_climate_mode_room_fan_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='light_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=20),
        ),
    ]
