# Generated by Django 4.2.27 on 2026-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_light_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ldr_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='led1_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='led2_status',
            field=models.BooleanField(default=False),
        ),
    ]
