# Generated by Django 4.2.27 on 2026-01-09 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_ldr_percentage_room_led1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='door_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='door_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='sensor_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('door_opened', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='rooms.room')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
