# Generated by Django 4.2.27 on 2026-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_ldr_percentage_room_led1_status_and_more'),
        ('accounts', '0003_merge_authentik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oidc_sub',
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_rooms',
            field=models.ManyToManyField(blank=True, help_text='Rooms this monitor can view. Leave empty for all rooms.', related_name='allowed_monitors', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
